version: '3'

services:
  db:
    image: postgres:14.0
    restart: always 
    environment:
      - POSTGRES_USER=sujaUser
      - POSTGRES_PASSWORD=sujaPassword 
    volumes:
      - suja_db_data:/var/lib/postgresql/data
    networks:
      - suja_backend_tier

  suja:
    restart: always
    build: .
    depends_on: 
      - db
    env_file: .env
    command: python manage.py runserver 0.0.0.0:8007
    links:
      - db:postgres
    volumes:
      - .:/app
    ports:
      - "8007:8007"
    expose:
      - "8009"
    networks:
      - suja_backend_tier

volumes:
  suja_db_data:
    driver: local 
  static_volume:
    driver: local

networks:
  suja_backend_tier: 
    driver: bridge
