# Generated by Django 4.2.7 on 2024-09-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ageis_app", "0054_jobs_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ageis_app.district",
            ),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="state",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ageis_app.state",
            ),
        ),
    ]
